# Generated by Django 2.2.6 on 2019-12-31 06:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dess',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='description'),
        ),
    ]
