# Generated by Django 2.2.8 on 2020-01-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
