# Generated by Django 2.2.8 on 2020-01-02 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_view_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rated',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
