# Generated by Django 2.2.8 on 2020-01-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='html',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
