# Generated by Django 2.2.8 on 2020-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_color_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='html',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
