# Generated by Django 2.2.8 on 2020-01-04 07:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.TextField(null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('image', models.ImageField(null=True, upload_to='blog/images/%Y/%m/%d')),
            ],
        ),
    ]
