# Generated by Django 2.2.6 on 2020-01-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_product_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_banner_1', models.BooleanField(blank=True, default=True, null=True)),
                ('show_characteristics', models.BooleanField(blank=True, default=True, null=True)),
                ('show_deals_featured', models.BooleanField(blank=True, default=True, null=True)),
                ('show_popular_categories', models.BooleanField(blank=True, default=True, null=True)),
                ('show_banner_2', models.BooleanField(blank=True, default=True, null=True)),
                ('show_new_arrivals', models.BooleanField(blank=True, default=True, null=True)),
                ('show_best_sellers', models.BooleanField(blank=True, default=True, null=True)),
                ('show_trends', models.BooleanField(blank=True, default=True, null=True)),
                ('show_latest_reviews', models.BooleanField(blank=True, default=True, null=True)),
                ('show_viewed', models.BooleanField(blank=True, default=True, null=True)),
                ('banner_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
